services:
  - type: web
    name: backend
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y unixodbc unixodbc-dev
      cd backend && pip install -r requirements.txt
    startCommand: |
      cd backend
      python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
      # MySQL Configuration
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        sync: false
      # ClickHouse Configuration
      - key: CLICKHOUSE_HOST
        sync: false
      - key: CLICKHOUSE_USER
        sync: false
      - key: CLICKHOUSE_PASSWORD
        sync: false
      - key: CLICKHOUSE_DATABASE
        sync: false
      # DuckDB Configuration
      - key: DUCKDB_PATH
        sync: false

  - type: web
    name: frontend
    env: node
    rootDir: my-app
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://text2sql-backend.onrender.com
